version: "2.4"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - URL=fleury.io
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=ovh
    volumes:
      - /home/paul/config/swag:/config
    networks:
      - proxy-network
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped


  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    depends_on:
      - pihole
    dns:
      - 172.29.0.15
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - SERVERURL=vpn.fleury.io #optional
      - PEERS=pauls_iPhone, pauls_iPad, pauls_mac, guest #optional
    volumes:
      - /home/paul/config/wireguard:/config
      - /lib/modules:/lib/modules
    networks:
      - proxy-network
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped


  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    volumes:
      - /home/paul/config/pihole/etc:/etc/pihole
      - /home/paul/config/pihole/dnsmasq.d:/etc/dnsmasq.d
    env_file:
      - .env
    networks:
      proxy-network:
        ipv4_address: 172.29.0.15
    restart: unless-stopped


  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/paul/config/code-server:/config
    networks:
      - proxy-network
    restart: unless-stopped


  notebook:
    image: jupyter/datascience-notebook:latest
    container_name: notebook
    volumes:
      - /home/paul/vps-services/notebook:/home/jovyan
    networks:
      - proxy-network
    restart: unless-stopped


  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    environment:
      - FTP_USER=admin
      - FTP_PASS=ftppass
      - PASV_ADDRESS=ftp.fleury.io
      - PASV_ADDR_RESOLVE=YES
      - LOG_STDOUT=YES
    volumes:
      - /home/paul/vps-services/vsftpd:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"


networks:
  proxy-network:
    name: proxy-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1

