version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/paul/config/code-server:/config
    ports:
      - 127.0.0.1:8443:8443
    restart: unless-stopped

  notebook:
    image: jupyter/datascience-notebook:latest
    container_name: notebook
    volumes:
      - /home/paul/vps-services/notebook:/home/jovyan
    ports:
      - 127.0.0.1:8888:8888
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=vpn.fleury.io #optional
      - PEERS=pauls_iPhone, pauls_iPad, pauls_mac, guest #optional
    volumes:
      - /home/paul/config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    environment:
      - FTP_USER=admin
      - FTP_PASS=ftppass
      - PASV_ADDRESS=ftp.fleury.io
      - PASV_ADDR_RESOLVE=YES
      - LOG_STDOUT=YES
    volumes:
      - /home/paul/vps-services/vsftpd:/home/vsftpd
      - /home/paul/config/vsftpd:/etc/vsftpd
    ports:
      - 20:20
      - 21:21
      - 21100-21110:21100-21110

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=fleury.io
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=ovh
    volumes:
      - /home/paul/config/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
